"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var admin_1 = require("../controllers/admin");
var auth_1 = require("../middleware/auth");
var router = (0, express_1.Router)();
router.get('/stats/revenue', auth_1.authMiddleware, auth_1.adminMiddleware, admin_1.getRevenue);
router.get('/stats/orders', auth_1.authMiddleware, auth_1.adminMiddleware, admin_1.getOrderCount);
router.get('/stats/products', auth_1.authMiddleware, auth_1.adminMiddleware, admin_1.getProductCount);
router.get('/stats/customers', auth_1.authMiddleware, auth_1.adminMiddleware, admin_1.getCustomerCount);
router.get('/orders/recent', auth_1.authMiddleware, auth_1.adminMiddleware, admin_1.getRecentOrders);
export default router; 