"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var auth_1 = require("../controllers/auth");
var auth_2 = require("../middleware/auth");
var router = (0, express_1.Router)();
router.post('/login', auth_1.loginUser);
router.post('/register', auth_1.registerUser);
router.get('/me', auth_2.authMiddleware, auth_1.getMe);
export default router; 