"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var meta_1 = require("../controllers/meta");
var router = (0, express_1.Router)();
router.get('/categories', meta_1.getCategories);
router.get('/colors', meta_1.getColors);
router.get('/materials', meta_1.getMaterials);
router.get('/room-types', meta_1.getRoomTypes);
export default router; 